language: node_js
node_js:
 - "node"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=quexten/sso-frontend
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - export REPO=quexten/sso-frontend
 - npm build
 - docker build -t $REPO:$TAG --build-arg BUILD_PATH=$TRAVIS_BUILD_DIR -f Dockerfile .
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi
 - docker push $REPO:$TAG
