version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       
      # Run build
      - run: yarn run build
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
           - dist
  deploy:
    requires:
      - build
    docker:
      - image: circleci/build-base:1.1
    steps:
      - run: git checkout master
      - attach_workspace:
          at: /tmp/workspace
      - run: cp /tmp/workspace/dist ./

workflows:
  version: 2
  build_deploy:
    jobs:
      - build 
      - deploy:
         requires:
          - build
         filters:
           branches:
             only: release
    
      


