version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       
      # Run build
      - run: yarn run build
      - persist_to_workspace:
          root: ~/repo
          paths:
           - dist
           - .circleci
  deploy:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: git checkout master
      - attach_workspace:
          at: /tmp/workspace
      - run: git config --global user.email ci@quexten.com
      - run: git config --global user.name CircleCI
      - run: git fetch --all
      - run: git reset --hard origin/master
      - run: cp -R ./.git ../.git
      - run: cd ..
      - run: rm -rf ./repo
      - run: cp -R /tmp/workspace/dist ./repo
      - run: cp -R /tmp/workspace/.circleci ./repo
      - run: cd ./repo
      - run: cp -R ../.git ./.git
      - run: git add .
      - run: return 1
      - run: git commit -m "Add dist files"
      - run: git push -q https://quexten:${GITHUB_TOKEN}@github.com/quexten/sso-frontend.git master
workflows:
  version: 2
  build_deploy:
    jobs:
      - build 
      - deploy:
         requires:
          - build
         filters:
           branches:
             only: release
    
      


